"use client";
import { FormEvent, useState } from "react";
type Step = { label?: string; title?: string; status?: string; note?: string; time?: string; completed?: boolean; done?: boolean };
type Progress = { query_code?: string; status?: string; public_note?: string; selected_result?: { name?: string }; progress?: Step[]; steps?: Step[] };
export function ProgressQuery() {
  const [value, setValue] = useState(""); const [data, setData] = useState<Progress | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function query(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); setData(null); try { const response = await fetch("/api/backend?path=progress/query", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query_code: value.trim() }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || "未找到该查询码"); setData(payload.progress || payload); } catch (cause) { setError(cause instanceof Error ? cause.message : "查询失败"); } finally { setLoading(false); } }
  const steps = data?.progress || data?.steps || [];
  return <div className="panel progress-box"><h2>输入查询码</h2><p className="notice">查询码仅用于查看项目进度，不会显示需求方联系人及联系方式。</p><form className="query-row" onSubmit={query}><input value={value} onChange={(event) => setValue(event.target.value)} required placeholder="例如：TNX-XXXXXX" aria-label="项目查询码" /><button className="button button-primary" disabled={loading}>{loading ? "查询中…" : "查询进度"}</button></form>{error && <div className="error-box">{error}</div>}{data && <div><div className="success-box"><small>当前状态</small><strong>{data.status || "平台审核中"}</strong><span>{data.selected_result?.name || data.public_note || "平台正在推进该项目"}</span></div><div className="timeline">{steps.map((step, index) => <div className={`timeline-item ${step.completed || step.done || step.status === "done" ? "done" : ""}`} key={`${step.label || step.title}-${index}`}><b>{step.label || step.title || `进度 ${index + 1}`}</b><span>{step.note || step.status || "待更新"}</span>{step.time && <small>{step.time}</small>}</div>)}</div></div>}</div>;
}
